In [2]:
import pandas as pd

In [52]:
reviews = pd.read_csv('./archive/Reviews.csv')

In [53]:
reviews = reviews.loc[:30]

In [54]:
reviews.drop(['Id', 'ProfileName', 'HelpfulnessNumerator', 'HelpfulnessDenominator', 'Time', 'Text', 'Summary'], inplace = True, axis = 1)

In [55]:
reviews.to_csv('./archive/test_30_record.csv', index=False)

In [56]:
df = pd.read_csv('./archive/test_30_record.csv')

In [57]:
df

     ProductId          UserId  Score
0   B001E4KFG0  A3SGXH7AUHU8GW      5
1   B00813GRG4  A1D87F6ZCVE5NK      1
2   B000LQOCH0   ABXLMWJIXXAIN      4
3   B000UA0QIQ  A395BORC6FGVXV      2
4   B006K2ZZ7K  A1UQRSCLF8GW1T      5
5   B006K2ZZ7K   ADT0SRK1MGOEU      4
6   B006K2ZZ7K  A1SP2KVKFXXRU1      5
7   B006K2ZZ7K  A3JRGQVEQN31IQ      5
8   B000E7L2R4  A1MZYO9TZK0BBI      5
9   B00171APVA  A21BT40VZCCYT4      5
10  B0001PB9FE  A3HDKO7OW0QNK4      5
11  B0009XLVG0  A2725IB4YY9JEB      5
12  B0009XLVG0   A327PCT23YH90      1
13  B001GVISJM  A18ECVX2RJ7HUE      4
14  B001GVISJM  A2MUGFV2TDQ47K      5
15  B001GVISJM  A1CZX3CP8IKQIJ      5
16  B001GVISJM  A3KLWF6WQ5BNYO      2
17  B001GVISJM   AFKW14U97Z6QO      5
18  B001GVISJM  A2A9X58G2GTBLP      5
19  B001GVISJM  A3IV7CL2C13K2U      5
20  B001GVISJM  A1WO0KGLPR5PV6      5
21  B001GVISJM   AZOF9E17RGZH8      5
22  B001GVISJM   ARYVQL4N737A1      5
23  B001GVISJM   AJ613OLZZUG7V      5
24  B001GVISJM  A22P2J09NJ9HKE      5
25  B001GVISJM  A3FONPR03H3PJS      5
26  B001GVISJM  A3RXAU2N8KV45G      1
27  B001GVISJM   AAAS38B98HMIK      4
28  B00144C10S  A2F4LZVGFLD1OB      5
29  B0001PB9FY  A3HDKO7OW0QNK4      5
30  B003F6UO7K   AFM0O9480F04W      5

In [58]:
df_2 = df.copy(deep=True)

In [59]:
df_2[df_2.UserId == 'A3HDKO7OW0QNK4']

     ProductId          UserId  Score
10  B0001PB9FE  A3HDKO7OW0QNK4      5
29  B0001PB9FY  A3HDKO7OW0QNK4      5

In [60]:
df_2[df_2.duplicated(['UserId'], keep=False)]

     ProductId          UserId  Score
10  B0001PB9FE  A3HDKO7OW0QNK4      5
29  B0001PB9FY  A3HDKO7OW0QNK4      5

In [61]:
df_2.to_csv(r'./archive/test_30_record.txt', header=None, index=None, sep='\t', mode='w')

In [66]:
# Mapper
import sys
import string
with open('./archive/test_30_record.txt') as f:
    contents = f.readlines()
    #print(contents)

    
i = 0

# read line from standard input
for line in contents:
    # removing leading/trailing whitespaces
    line = line.strip()
    # split the current line into words
    productId, userId, score = line.split("\t")

    productId = productId.strip()
    userId = userId.strip()
    score = score.strip()
    
    print('%s\t%s\t%s' % (userId, productId, score))
    
    with open('./archive/test_30_output.txt', 'a') as w:
            line = userId + '\t' + productId + '\t' + score + '\n'
            w.writelines(line)

    
w.close()
f.close()

A3SGXH7AUHU8GW	B001E4KFG0	5
A1D87F6ZCVE5NK	B00813GRG4	1
ABXLMWJIXXAIN	B000LQOCH0	4
A395BORC6FGVXV	B000UA0QIQ	2
A1UQRSCLF8GW1T	B006K2ZZ7K	5
ADT0SRK1MGOEU	B006K2ZZ7K	4
A1SP2KVKFXXRU1	B006K2ZZ7K	5
A3JRGQVEQN31IQ	B006K2ZZ7K	5
A1MZYO9TZK0BBI	B000E7L2R4	5
A21BT40VZCCYT4	B00171APVA	5
A3HDKO7OW0QNK4	B0001PB9FE	5
A2725IB4YY9JEB	B0009XLVG0	5
A327PCT23YH90	B0009XLVG0	1
A18ECVX2RJ7HUE	B001GVISJM	4
A2MUGFV2TDQ47K	B001GVISJM	5
A1CZX3CP8IKQIJ	B001GVISJM	5
A3KLWF6WQ5BNYO	B001GVISJM	2
AFKW14U97Z6QO	B001GVISJM	5
A2A9X58G2GTBLP	B001GVISJM	5
A3IV7CL2C13K2U	B001GVISJM	5
A1WO0KGLPR5PV6	B001GVISJM	5
AZOF9E17RGZH8	B001GVISJM	5
ARYVQL4N737A1	B001GVISJM	5
AJ613OLZZUG7V	B001GVISJM	5
A22P2J09NJ9HKE	B001GVISJM	5
A3FONPR03H3PJS	B001GVISJM	5
A3RXAU2N8KV45G	B001GVISJM	1
AAAS38B98HMIK	B001GVISJM	4
A2F4LZVGFLD1OB	B00144C10S	5
A3HDKO7OW0QNK4	B0001PB9FY	5
AFM0O9480F04W	B003F6UO7K	5

In [76]:
# Reducer
with open('./archive/test_30_output.txt') as f:
    contents = f.readlines()
    
user_product_score = {}

# input comes from STDIN
# note: this is the output from the mapper
for line in contents:

    # as usual, remove leading/trailing spaces
    line = line.strip()

    # parse the input elements
    userId, productId, score = line.split("\t")

    # convert count (currently a string) to int
    try:
        score = int(score)
    except ValueError:
        # count was not a number, in this case is just int
        continue

    # initialize word that were not seen befor with 0
    if userId not in user_product_score:
        user_product_score[userId] = {}
    
    user_product_score[userId][productId] = score

#print(user_product_score.items())
#print(user_product_score['A3SGXH7AUHU8GW'].items())

for userId in sorted(user_product_score.keys()):
    print('%s' % userId)
    for productID in sorted(user_product_score[userId].items(), key=lambda x: x[1], reverse = True)[:5]:
        print('\t%s\t%i' % (productID[0], productID[1]))

A18ECVX2RJ7HUE
	B001GVISJM	4
A1CZX3CP8IKQIJ
	B001GVISJM	5
A1D87F6ZCVE5NK
	B00813GRG4	1
A1MZYO9TZK0BBI
	B000E7L2R4	5
A1SP2KVKFXXRU1
	B006K2ZZ7K	5
A1UQRSCLF8GW1T
	B006K2ZZ7K	5
A1WO0KGLPR5PV6
	B001GVISJM	5
A21BT40VZCCYT4
	B00171APVA	5
A22P2J09NJ9HKE
	B001GVISJM	5
A2725IB4YY9JEB
	B0009XLVG0	5
A2A9X58G2GTBLP
	B001GVISJM	5
A2F4LZVGFLD1OB
	B00144C10S	5
A2MUGFV2TDQ47K
	B001GVISJM	5
A327PCT23YH90
	B0009XLVG0	1
A395BORC6FGVXV
	B000UA0QIQ	2
A3FONPR03H3PJS
	B001GVISJM	5
A3HDKO7OW0QNK4
	B0001PB9FE	5
	B0001PB9FY	5
A3IV7CL2C13K2U
	B001GVISJM	5
A3JRGQVEQN31IQ
	B006K2ZZ7K	5
A3KLWF6WQ5BNYO
	B001GVISJM	2
A3RXAU2N8KV45G
	B001GVISJM	1
A3SGXH7AUHU8GW
	B001E4KFG0	5
AAAS38B98HMIK
	B001GVISJM	4
ABXLMWJIXXAIN
	B000LQOCH0	4
ADT0SRK1MGOEU
	B006K2ZZ7K	4
AFKW14U97Z6QO
	B001GVISJM	5
AFM0O9480F04W
	B003F6UO7K	5
AJ613OLZZUG7V
	B001GVISJM	5
ARYVQL4N737A1
	B001GVISJM	5
AZOF9E17RGZH8
	B001GVISJM	5