In [1]:
import pandas as pd
import numpy as np

In [ ]:
reviews = pd.read_csv('./archive/Reviews.csv')

In [30]:
reviews.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [ ]:
reviews.isnull().sum()

In [46]:
reviews.UserId[reviews.Summary.isnull()]

33958     A3TJPSWY2HE4BS
40548     A3TJPSWY2HE4BS
101106    A3TJPSWY2HE4BS
102979    A3TJPSWY2HE4BS
117515    A3TJPSWY2HE4BS
155712    A3TJPSWY2HE4BS
178290    A3TJPSWY2HE4BS
198474    A3TJPSWY2HE4BS
212691    A3TJPSWY2HE4BS
237565    A15AMT9T9A1309
293906    A3TJPSWY2HE4BS
299495    A3TJPSWY2HE4BS
300961    A3TJPSWY2HE4BS
333556    A3TJPSWY2HE4BS
352043    A3TJPSWY2HE4BS
357215    A3TJPSWY2HE4BS
357814    A3TJPSWY2HE4BS
360782    A3TJPSWY2HE4BS
379473    A3TJPSWY2HE4BS
380558    A3TJPSWY2HE4BS
381313    A3TJPSWY2HE4BS
386283    A3TJPSWY2HE4BS
392529    A22R17YPXEULEZ
484367    A3TJPSWY2HE4BS
486640    A3TJPSWY2HE4BS
503260    A3TJPSWY2HE4BS
530716    A3TJPSWY2HE4BS
Name: UserId, dtype: object

In [ ]:
reviews[reviews.ProfileName.isnull()]

In [48]:
reviews[reviews.UserId == 'A22R17YPXEULEZ']

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
392529,392530,B001H9XOEW,A22R17YPXEULEZ,Liz Wong,0,0,3,1334534400,NaN,I like the product and tried it before I pucha...

In [38]:
len(reviews[reviews.UserId == 'A3TJPSWY2HE4BS'])

25

In [33]:
reviews[reviews.UserId == 'ABXLMWJIXXAIN']

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
320690,320691,B000CQ26E0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",0,0,4,1187740800,"Fast, Easy and organic","For speed and wholesome goodness, Annie's can ..."
468953,468954,B004DMGQKE,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",0,0,5,1351209600,Awesome service and great products,We sent this product as a gift to my husband's...

In [31]:
reviews[reviews.UserId == 'A395BORC6FGVXV']

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
136303,136304,B002Y7526Y,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
544172,544173,B000U9WZ54,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...

In [51]:
reviews.loc[:10]

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...
5,6,B006K2ZZ7K,ADT0SRK1MGOEU,Twoapennything,0,0,4,1342051200,Nice Taffy,I got a wild hair for taffy and ordered this f...
6,7,B006K2ZZ7K,A1SP2KVKFXXRU1,David C. Sullivan,0,0,5,1340150400,Great! Just as good as the expensive brands!,This saltwater taffy had great flavors and was...
7,8,B006K2ZZ7K,A3JRGQVEQN31IQ,Pamela G. Williams,0,0,5,1336003200,"Wonderful, tasty taffy",This taffy is so good. It is very soft and ch...
8,9,B000E7L2R4,A1MZYO9TZK0BBI,R. James,1,1,5,1322006400,Yay Barley,Right now I'm mostly just sprouting this so my...
9,10,B00171APVA,A21BT40VZCCYT4,Carol A. Reed,0,0,5,1351209600,Healthy Dog Food,This is a very healthy dog food. Good for thei...
10,11,B0001PB9FE,A3HDKO7OW0QNK4,Canadian Fan,1,1,5,1107820800,The Best Hot Sauce in the World,I don't know if it's the cactus or the tequila...

In [121]:
test = reviews.loc[:10]

In [122]:
df_2 = test.copy(deep=True)

In [123]:
df_2.drop(['Id', 'ProfileName', 'HelpfulnessNumerator', 'HelpfulnessDenominator', 'Summary'], inplace = True, axis = 1)

In [124]:
from datetime import datetime

In [125]:
type(test.Time[0])

numpy.int64

In [126]:
ts = int(test.Time[0])
print(datetime.utcfromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S'))

2011-04-27 00:00:00

In [127]:
#df_2.Time = df_2.Time.apply(lambda t: datetime.utcfromtimestamp(int(t)).strftime('%Y-%m-%d'))
df_2.Time = df_2.Time.apply(lambda t: datetime.utcfromtimestamp(int(t)).strftime('%Y'))

In [128]:
test.Time

0     1303862400
1     1346976000
2     1219017600
3     1307923200
4     1350777600
5     1342051200
6     1340150400
7     1336003200
8     1322006400
9     1351209600
10    1107820800
Name: Time, dtype: int64

In [129]:
df_2

,ProductId,UserId,Score,Time,Text
0,B001E4KFG0,A3SGXH7AUHU8GW,5,2011,I have bought several of the Vitality canned d...
1,B00813GRG4,A1D87F6ZCVE5NK,1,2012,Product arrived labeled as Jumbo Salted Peanut...
2,B000LQOCH0,ABXLMWJIXXAIN,4,2008,This is a confection that has been around a fe...
3,B000UA0QIQ,A395BORC6FGVXV,2,2011,If you are looking for the secret ingredient i...
4,B006K2ZZ7K,A1UQRSCLF8GW1T,5,2012,Great taffy at a great price. There was a wid...
5,B006K2ZZ7K,ADT0SRK1MGOEU,4,2012,I got a wild hair for taffy and ordered this f...
6,B006K2ZZ7K,A1SP2KVKFXXRU1,5,2012,This saltwater taffy had great flavors and was...
7,B006K2ZZ7K,A3JRGQVEQN31IQ,5,2012,This taffy is so good. It is very soft and ch...
8,B000E7L2R4,A1MZYO9TZK0BBI,5,2011,Right now I'm mostly just sprouting this so my...
9,B00171APVA,A21BT40VZCCYT4,5,2012,This is a very healthy dog food. Good for thei...
10,B0001PB9FE,A3HDKO7OW0QNK4,5,2005,I don't know if it's the cactus or the tequila...

In [115]:
df_2.to_csv('./archive/test_10_record.csv', index=False)

In [130]:
df_2.drop(['ProductId', 'UserId', 'Score'], inplace = True, axis = 1)

In [132]:
df_2

    Time                                               Text
0   2011  I have bought several of the Vitality canned d...
1   2012  Product arrived labeled as Jumbo Salted Peanut...
2   2008  This is a confection that has been around a fe...
3   2011  If you are looking for the secret ingredient i...
4   2012  Great taffy at a great price.  There was a wid...
5   2012  I got a wild hair for taffy and ordered this f...
6   2012  This saltwater taffy had great flavors and was...
7   2012  This taffy is so good.  It is very soft and ch...
8   2011  Right now I'm mostly just sprouting this so my...
9   2012  This is a very healthy dog food. Good for thei...
10  2005  I don't know if it's the cactus or the tequila...

In [134]:
df_2.to_csv(r'./archive/test_10_record.txt', header=None, index=None, sep='\t', mode='w')

In [56]:
pd.read_csv('./archive/test_10_record.csv')

,ProductId,UserId,Score,Time,Text
0,B001E4KFG0,A3SGXH7AUHU8GW,5,2011-04-27,I have bought several of the Vitality canned d...
1,B00813GRG4,A1D87F6ZCVE5NK,1,2012-09-07,Product arrived labeled as Jumbo Salted Peanut...
2,B000LQOCH0,ABXLMWJIXXAIN,4,2008-08-18,This is a confection that has been around a fe...
3,B000UA0QIQ,A395BORC6FGVXV,2,2011-06-13,If you are looking for the secret ingredient i...
4,B006K2ZZ7K,A1UQRSCLF8GW1T,5,2012-10-21,Great taffy at a great price. There was a wid...
5,B006K2ZZ7K,ADT0SRK1MGOEU,4,2012-07-12,I got a wild hair for taffy and ordered this f...
6,B006K2ZZ7K,A1SP2KVKFXXRU1,5,2012-06-20,This saltwater taffy had great flavors and was...
7,B006K2ZZ7K,A3JRGQVEQN31IQ,5,2012-05-03,This taffy is so good. It is very soft and ch...
8,B000E7L2R4,A1MZYO9TZK0BBI,5,2011-11-23,Right now I'm mostly just sprouting this so my...
9,B00171APVA,A21BT40VZCCYT4,5,2012-10-26,This is a very healthy dog food. Good for thei...
10,B0001PB9FE,A3HDKO7OW0QNK4,5,2005-02-08,I don't know if it's the cactus or the tequila...

In [57]:
anno_parola = {}

In [58]:
words = {}

In [59]:
words['ciao'] = 1

In [60]:
words['sono'] = 2

In [61]:
words['a'] = 3

In [62]:
anno_parola[2011] = words

In [70]:
anno_parola[2010] = words

In [103]:
anno_parola

{2011: {'ciao': 1, 'sono': 2, 'a': 3, 'c': 0},
 2010: {'ciao': 1, 'sono': 2, 'a': 3, 'c': 0}}

In [72]:
del anno_parola[1]

KeyError: 1

In [175]:
anno_parola[2011]['ciao']

1

In [64]:
anno_parola[2011]['c'] = 0

In [94]:
anno_parola[2011].items()

dict_items([('ciao', 1), ('sono', 2), ('a', 3), ('c', 0)])

In [108]:
# Orinare dizionario di dizionario
sort_orders = sorted(anno_parola[2011].items(), key=lambda x: x[1], reverse = True)[:2]

In [100]:
sort_orders

[('a', 3), ('sono', 2)]

In [101]:
for year, words in anno_parola.items():
    print(words)

{'ciao': 1, 'sono': 2, 'a': 3, 'c': 0}
{'ciao': 1, 'sono': 2, 'a': 3, 'c': 0}

In [136]:
ordered = sorted(words.items(), key=lambda x: x[1], reverse = True)

In [139]:
ordered_2 = sorted(words.values(), reverse = True)

In [140]:
ordered_2

[3, 2, 1, 0]

In [137]:
ordered

[('a', 3), ('sono', 2), ('ciao', 1), ('c', 0)]

In [151]:
for year, words in anno_parola.items():
    for i in sorted(words.items(), key=lambda x: x[1], reverse = True)[:4]:
        print(i[1])
        print("%i %s %s" % (year, i[0], i[1]))

3
2011 a 3
2
2011 sono 2
1
2011 ciao 1
0
2011 c 0
3
2010 a 3
2
2010 sono 2
1
2010 ciao 1
0
2010 c 0

In [152]:
if 'ciao' in anno_parola[2011]:
    print("c")

c

In [154]:
year_word = {}

In [155]:
year_word[2012] = set()

In [167]:
year_word

{2012: {('Ciao', 1), ('sono', 2)}}

In [157]:
year_word[2012].add(('Ciao', 1))

In [159]:
year_word[2012].add(('sono', 2))

In [19]:
def remove_tags(text):
    return ''.join(xml.etree.ElementTree.fromstring(text).itertext())

In [27]:
import re
# as per recommendation from @freylis, compile once only
CLEANR = re.compile('<.*?>') 

def cleanhtml(raw_html): 
    return re.sub(CLEANR, ' ', raw_html)

In [179]:
import sys
import string
with open('./archive/test_10_record.txt') as f:
    contents = f.readlines()
    #print(contents)

    
i = 0

# read line from standard input
for line in contents:
    # removing leading/trailing whitespaces
    line = line.strip()
    # split the current line into words
    year, words = line.split("\t")
    
    # remove html tag inside text
    words = cleanhtml(words)
    # replace dot with withespace
    words = words.replace(".", " ")
    
    # remove punctuation
    words = words.translate(str.maketrans('', '', string.punctuation))
    words = re.sub(' +', ' ', words)
    words = words.strip()
    # splittare riga in words per il campo text
    words = words.split(" ")
    
    for word in words:
        # write in standard output the mapping word -> 1
        # in the form of tab-separated pairs
        with open('./archive/test_output.txt', 'a') as w:
            line = year + '\t' + word.lower() + '\t' + str(1) + '\n'
            w.writelines(line)
        print('%s\t%s\t%i' % (year, word.lower(), 1))
w.close()
f.close()

2011	i	1
2011	have	1
2011	bought	1
2011	several	1
2011	of	1
2011	the	1
2011	vitality	1
2011	canned	1
2011	dog	1
2011	food	1
2011	products	1
2011	and	1
2011	have	1
2011	found	1
2011	them	1
2011	all	1
2011	to	1
2011	be	1
2011	of	1
2011	good	1
2011	quality	1
2011	the	1
2011	product	1
2011	looks	1
2011	more	1
2011	like	1
2011	a	1
2011	stew	1
2011	than	1
2011	a	1
2011	processed	1
2011	meat	1
2011	and	1
2011	it	1
2011	smells	1
2011	better	1
2011	my	1
2011	labrador	1
2011	is	1
2011	finicky	1
2011	and	1
2011	she	1
2011	appreciates	1
2011	this	1
2011	product	1
2011	better	1
2011	than	1
2011	most	1
2012	product	1
2012	arrived	1
2012	labeled	1
2012	as	1
2012	jumbo	1
2012	salted	1
2012	peanuts	1
2012	the	1
2012	peanuts	1
2012	were	1
2012	actually	1
2012	small	1
2012	sized	1
2012	unsalted	1
2012	not	1
2012	sure	1
2012	if	1
2012	this	1
2012	was	1
2012	an	1
2012	error	1
2012	or	1
2012	if	1
2012	the	1
2012	vendor	1
2012	intended	1
2012	to	1
2012	represent	1
2012	the	1
2012	product	1
2012	as	1
2012	jumbo	1
2008	this	1
2008	is	1
2008	a	1
2008	confection	1
2008	that	1
2008	has	1
2008	been	1
2008	around	1
2008	a	1
2008	few	1
2008	centuries	1
2008	it	1
2008	is	1
2008	a	1
2008	light	1
2008	pillowy	1
2008	citrus	1
2008	gelatin	1
2008	with	1
2008	nuts	1
2008	in	1
2008	this	1
2008	case	1
2008	filberts	1
2008	and	1
2008	it	1
2008	is	1
2008	cut	1
2008	into	1
2008	tiny	1
2008	squares	1
2008	and	1
2008	then	1
2008	liberally	1
2008	coated	1
2008	with	1
2008	powdered	1
2008	sugar	1
2008	and	1
2008	it	1
2008	is	1
2008	a	1
2008	tiny	1
2008	mouthful	1
2008	of	1
2008	heaven	1
2008	not	1
2008	too	1
2008	chewy	1
2008	and	1
2008	very	1
2008	flavorful	1
2008	i	1
2008	highly	1
2008	recommend	1
2008	this	1
2008	yummy	1
2008	treat	1
2008	if	1
2008	you	1
2008	are	1
2008	familiar	1
2008	with	1
2008	the	1
2008	story	1
2008	of	1
2008	c	1
2008	s	1
2008	lewis	1
2008	the	1
2008	lion	1
2008	the	1
2008	witch	1
2008	and	1
2008	the	1
2008	wardrobe	1
2008	this	1
2008	is	1
2008	the	1
2008	treat	1
2008	that	1
2008	seduces	1
2008	edmund	1
2008	into	1
2008	selling	1
2008	out	1
2008	his	1
2008	brother	1
2008	and	1
2008	sisters	1
2008	to	1
2008	the	1
2008	witch	1
2011	if	1
2011	you	1
2011	are	1
2011	looking	1
2011	for	1
2011	the	1
2011	secret	1
2011	ingredient	1
2011	in	1
2011	robitussin	1
2011	i	1
2011	believe	1
2011	i	1
2011	have	1
2011	found	1
2011	it	1
2011	i	1
2011	got	1
2011	this	1
2011	in	1
2011	addition	1
2011	to	1
2011	the	1
2011	root	1
2011	beer	1
2011	extract	1
2011	i	1
2011	ordered	1
2011	which	1
2011	was	1
2011	good	1
2011	and	1
2011	made	1
2011	some	1
2011	cherry	1
2011	soda	1
2011	the	1
2011	flavor	1
2011	is	1
2011	very	1
2011	medicinal	1
2012	great	1
2012	taffy	1
2012	at	1
2012	a	1
2012	great	1
2012	price	1
2012	there	1
2012	was	1
2012	a	1
2012	wide	1
2012	assortment	1
2012	of	1
2012	yummy	1
2012	taffy	1
2012	delivery	1
2012	was	1
2012	very	1
2012	quick	1
2012	if	1
2012	your	1
2012	a	1
2012	taffy	1
2012	lover	1
2012	this	1
2012	is	1
2012	a	1
2012	deal	1
2012	i	1
2012	got	1
2012	a	1
2012	wild	1
2012	hair	1
2012	for	1
2012	taffy	1
2012	and	1
2012	ordered	1
2012	this	1
2012	five	1
2012	pound	1
2012	bag	1
2012	the	1
2012	taffy	1
2012	was	1
2012	all	1
2012	very	1
2012	enjoyable	1
2012	with	1
2012	many	1
2012	flavors	1
2012	watermelon	1
2012	root	1
2012	beer	1
2012	melon	1
2012	peppermint	1
2012	grape	1
2012	etc	1
2012	my	1
2012	only	1
2012	complaint	1
2012	is	1
2012	there	1
2012	was	1
2012	a	1
2012	bit	1
2012	too	1
2012	much	1
2012	redblack	1
2012	licoriceflavored	1
2012	pieces	1
2012	just	1
2012	not	1
2012	my	1
2012	particular	1
2012	favorites	1
2012	between	1
2012	me	1
2012	my	1
2012	kids	1
2012	and	1
2012	my	1
2012	husband	1
2012	this	1
2012	lasted	1
2012	only	1
2012	two	1
2012	weeks	1
2012	i	1
2012	would	1
2012	recommend	1
2012	this	1
2012	brand	1
2012	of	1
2012	taffy	1
2012	it	1
2012	was	1
2012	a	1
2012	delightful	1
2012	treat	1
2012	this	1
2012	saltwater	1
2012	taffy	1
2012	had	1
2012	great	1
2012	flavors	1
2012	and	1
2012	was	1
2012	very	1
2012	soft	1
2012	and	1
2012	chewy	1
2012	each	1
2012	candy	1
2012	was	1
2012	individually	1
2012	wrapped	1
2012	well	1
2012	none	1
2012	of	1
2012	the	1
2012	candies	1
2012	were	1
2012	stuck	1
2012	together	1
2012	which	1
2012	did	1
2012	happen	1
2012	in	1
2012	the	1
2012	expensive	1
2012	version	1
2012	fralingers	1
2012	would	1
2012	highly	1
2012	recommend	1
2012	this	1
2012	candy	1
2012	i	1
2012	served	1
2012	it	1
2012	at	1
2012	a	1
2012	beachthemed	1
2012	party	1
2012	and	1
2012	everyone	1
2012	loved	1
2012	it	1
2012	this	1
2012	taffy	1
2012	is	1
2012	so	1
2012	good	1
2012	it	1
2012	is	1
2012	very	1
2012	soft	1
2012	and	1
2012	chewy	1
2012	the	1
2012	flavors	1
2012	are	1
2012	amazing	1
2012	i	1
2012	would	1
2012	definitely	1
2012	recommend	1
2012	you	1
2012	buying	1
2012	it	1
2012	very	1
2012	satisfying	1
2011	right	1
2011	now	1
2011	im	1
2011	mostly	1
2011	just	1
2011	sprouting	1
2011	this	1
2011	so	1
2011	my	1
2011	cats	1
2011	can	1
2011	eat	1
2011	the	1
2011	grass	1
2011	they	1
2011	love	1
2011	it	1
2011	i	1
2011	rotate	1
2011	it	1
2011	around	1
2011	with	1
2011	wheatgrass	1
2011	and	1
2011	rye	1
2011	too	1
2012	this	1
2012	is	1
2012	a	1
2012	very	1
2012	healthy	1
2012	dog	1
2012	food	1
2012	good	1
2012	for	1
2012	their	1
2012	digestion	1
2012	also	1
2012	good	1
2012	for	1
2012	small	1
2012	puppies	1
2012	my	1
2012	dog	1
2012	eats	1
2012	her	1
2012	required	1
2012	amount	1
2012	at	1
2012	every	1
2012	feeding	1
2005	i	1
2005	dont	1
2005	know	1
2005	if	1
2005	its	1
2005	the	1
2005	cactus	1
2005	or	1
2005	the	1
2005	tequila	1
2005	or	1
2005	just	1
2005	the	1
2005	unique	1
2005	combination	1
2005	of	1
2005	ingredients	1
2005	but	1
2005	the	1
2005	flavour	1
2005	of	1
2005	this	1
2005	hot	1
2005	sauce	1
2005	makes	1
2005	it	1
2005	one	1
2005	of	1
2005	a	1
2005	kind	1
2005	we	1
2005	picked	1
2005	up	1
2005	a	1
2005	bottle	1
2005	once	1
2005	on	1
2005	a	1
2005	trip	1
2005	we	1
2005	were	1
2005	on	1
2005	and	1
2005	brought	1
2005	it	1
2005	back	1
2005	home	1
2005	with	1
2005	us	1
2005	and	1
2005	were	1
2005	totally	1
2005	blown	1
2005	away	1
2005	when	1
2005	we	1
2005	realized	1
2005	that	1
2005	we	1
2005	simply	1
2005	couldnt	1
2005	find	1
2005	it	1
2005	anywhere	1
2005	in	1
2005	our	1
2005	city	1
2005	we	1
2005	were	1
2005	bummed	1
2005	now	1
2005	because	1
2005	of	1
2005	the	1
2005	magic	1
2005	of	1
2005	the	1
2005	internet	1
2005	we	1
2005	have	1
2005	a	1
2005	case	1
2005	of	1
2005	the	1
2005	sauce	1
2005	and	1
2005	are	1
2005	ecstatic	1
2005	because	1
2005	of	1
2005	it	1
2005	if	1
2005	you	1
2005	love	1
2005	hot	1
2005	sauce	1
2005	i	1
2005	mean	1
2005	really	1
2005	love	1
2005	hot	1
2005	sauce	1
2005	but	1
2005	dont	1
2005	want	1
2005	a	1
2005	sauce	1
2005	that	1
2005	tastelessly	1
2005	burns	1
2005	your	1
2005	throat	1
2005	grab	1
2005	a	1
2005	bottle	1
2005	of	1
2005	tequila	1
2005	picante	1
2005	gourmet	1
2005	de	1
2005	inclan	1
2005	just	1
2005	realize	1
2005	that	1
2005	once	1
2005	you	1
2005	taste	1
2005	it	1
2005	you	1
2005	will	1
2005	never	1
2005	want	1
2005	to	1
2005	use	1
2005	any	1
2005	other	1
2005	sauce	1
2005	thank	1
2005	you	1
2005	for	1
2005	the	1
2005	personal	1
2005	incredible	1
2005	service	1

In [167]:
testo = 'ciao...ciao.ciao.'
testo = testo.replace(".", " ")
print(testo)
testo = re.sub(' +', ' ', testo)
print(testo)
testo = testo.strip()
print(testo)

ciao   ciao ciao
ciao ciao ciao
ciao ciao ciao

In [157]:
firstString = "abc"
secondString = "def"
thirdString = "."
string = "abc"
print(string.maketrans('', thirdString))

ValueError: the first two maketrans arguments must have equal length

In [174]:
with open('./archive/test_output.txt') as f:
    contents = f.readlines()
year_words = {}

# input comes from STDIN
# note: this is the output from the mapper
for line in contents:

    # as usual, remove leading/trailing spaces
    line = line.strip()

    # parse the input elements
    year, current_word, current_count = line.split("\t")

    # convert count (currently a string) to int
    try:
        current_count = int(current_count)
        year = int(year)
    except ValueError:
        # count was not a number, in this case is just int
        continue

    # initialize word that were not seen befor with 0
    if year not in year_words:
        year_words[year] = {}
    
    if current_word not in year_words[year]:
        year_words[year][current_word] = 0
    
    year_words[year][current_word] += current_count

for year, words in year_words.items():
    print('%i' % year)
    for word in sorted(words.items(), key=lambda x: x[1], reverse = True)[:10]:
        print('\t%s\t%i' % (word[0], word[1]))

2011
	i	6
	the	6
	and	5
	it	4
	have	3
	this	3
	of	2
	found	2
	to	2
	good	2
2012
	this	9
	a	9
	was	8
	taffy	8
	the	7
	very	6
	and	6
	is	5
	my	5
	it	5
2008
	and	6
	the	6
	is	5
	this	4
	a	4
	it	3
	with	3
	that	2
	into	2
	tiny	2
2005
	the	8
	of	8
	sauce	6
	a	6
	we	6
	it	5
	you	4
	hot	3
	were	3
	and	3